name: CI

on:
  push:
    paths:
      - '.github/workflows/ci.yaml'
      - 'Mifare Classic Tool/**'
  pull_request:
    paths:
      - '.github/workflows/ci.yaml'
      - 'Mifare Classic Tool/**'

env:
  PROJECT_PATH: Mifare Classic Tool

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle/wrapper/gradle-wrapper.properties', '**/buildSrc/src/main/kotlin/**.kt') }}
      - name: Build
        working-directory: ${{ env.PROJECT_PATH }}
        run: ./gradlew --parallel assembleRelease
